# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0002_auto_20160424_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country_id',
            new_name='country',
        ),
    ]
